### ISSUE TITLE
Update readme as request.el is pointing to your fork

### ISSUE THREAD

**Issue by shackra** [abingham/emacs-traad#1]

**Comment by abingham** [comment]
I've [removed the note about request.el](bcf9260fb8b9216ec1c455f673270049be7ccb38). Is that enough?

**Comment by shackra** [comment]
I hope so, Austin from Austin, Texas!

El lunes 04 de enero del 2016 a las 0155 horas, abingham escribió:

> I've [removed the note about request.el](bcf9260fb8b9216ec1c455f673270049be7ccb38). Is that enough?
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/abingham/emacs-traad/issues/1#issuecomment-168605343


-- 
👋 Pax et bonum.
Jorge Araya Navarro
https://es.gravatar.com/shackra

**Comment by abingham** [comment]
:)
