### ISSUE TITLE
File should refresh after refactor

### ISSUE THREAD

**Issue by thomassross** [abingham/emacs-traad#10]
The file doesn't seem to refresh after a `traad-rename` operation, making it look like the file has not been refactored

**Comment by abingham** [comment]
This is something I've thought about on and off for a while. See, for example, [this issue](https://github.com/abingham/traad/issues/26) from back before I split the emacs client into its own project. The main complexity is that we need to figure out all of the buffers that are affected; it's not always just the current buffer (though of course that one should always be refreshed). 

I would bet that the infrastructure (i.e. rope, request.el, etc.) have matured to the point where we can get the information we need from the traad server. Someone just needs to do the work.

An alternative that might improve things for you is to just turn on auto-revert. That's what I do right now, and it works pretty well.

**Comment by abingham** [comment]
@thomassross This should be largely fixed now. A few international flights gave me the uniterrupted time to sort this out. Basically, refactorings are now done in three phases:

1. First we ask the server for the changes that will be performed.
2. Then we ask for those change to be performed
3. Finally, we refresh the buffers which were indicated in (1).

From what I can tell this works reasonably well, though it's not (yet) optimal. Sometimes the refresh/revert takes longer than I'd like. I need to investigate this.

Also, I haven't yet sorted out what to do about unsaved changes. If you do a renaming on a file with unsaved changes, the traad server will see the stale version of the file on disk. I *think* what I want to do a) look for unsaved buffers in the changes returned from the server and b) query the user if they want to save buffers first. If they say no, then we'll probably want to cancel the refactoring. Or maybe that behavior should be configurable.

In any event, take the latest code (both server and emacs client) for a spin and let me know how it works for you.
