### ISSUE TITLE
virtualenvwrapper dependency

### ISSUE THREAD

**Issue by skliarpawlo** [abingham/emacs-traad#19]
Hi, I'm wondering why emacs-traad strictly depends in virtualenvwrapper. I don't use virutalenvs because I run everything inside docker container, so I install everything "globally" to container. But when I'm trying to use emacs-traad it's not quite happy about this. Wondering if there is any workaround for my case. Thanks

**Comment by abingham** [comment]
You should be able to set `traad-server-program` to the path of the `traad` executable you want to use. When that variable is not `nil`, then it's used as is to run the server, i.e. without trying to use a virtual environment. 

If that doesn't work for you, then there's a bug in the client.

**Comment by abingham** [comment]
With that said, `traad-install-server` does have a requirement on virtual environment. It tries to do the "normal" thing, and that's to install `traad` into a venv.

**Comment by skliarpawlo** [comment]
Thanks for you response yeah that works for me. Before that I ended up with just mimicing what it requires in Dockerfile steps which also worked, but a little hacky.
