### ISSUE TITLE
Functions need more documentation in relationship with Rope

### ISSUE THREAD

**Issue by shackra** [abingham/emacs-traad#20]
As myself, not many users know Rope in-deep and what it has to offer.

I was thinking that each function that do something, like `traad-handle-long-imports`, should have in the function documentation an explanation of what it does, say, taken from the Rope project itself:

> Handle long imports command trys to make long imports look better by transforming `import pkg1.pkg2.pkg3.pkg4.mod1` to `from pkg1.pkg2.pkg3.pkg4 import mod1`. Long imports can be identified either by having lots of dots or being very long. The default configuration considers imported modules with more than 2 dots or with more than 27 characters to be long.

**Comment by abingham** [comment]
That seems reasonable. I'm open to PRs.

**Comment by jcaw** [comment]
How are these?

**Comment by abingham** [comment]
@shackra Does the PR by @jcaw work for you? If so, please close this out. Thanks!

**Comment by shackra** [comment]
Yup, this PR is a God sent

thank you @jcaw

**Comment by jcaw** [comment]
@shackra no worries! Happy to help. :)
