### ISSUE TITLE
Add a method parameter

### ISSUE THREAD

**Issue by vindarel** [abingham/emacs-traad#5]
Let's continue the discussion started at https://github.com/abingham/emacs-traad/issues/3#issuecomment-284638814

Rope has an [ArgumentAdder](https://github.com/python-rope/rope/blob/master/rope/refactor/change_signature.py#L218) class.

I tried sthg for traad. edit- oops, let's go on traad first.

**Comment by abingham** [comment]
The work on traad looks good. As soon as it's ready, I think the work here will be pretty simple.

**Comment by vindarel** [comment]
I wonder a bit on the workflow.
On rope, it looks like the index argument is compulsory
```
definition_info.args_with_defaults.insert(self.index,
                                                  (self.name, self.default))
```
So adding an argument would require:
- to choose the index
- to add a new arg
- and a new value (or we skip this step and directly type "foo=bar" in the new arg prompt)

but this could be boring since the index and the new value are optional in many cases.
Well, first: do this :p 

Then discuss:
Is the index really mandatory ?

I wrote a similar function: https://gitlab.com/vindarel/redbaron4emacs/blob/master/red4emacs.el#L184 where it asks only for a new arg (possibly arg=value) and where the custom python code inserts it at the right place. (it doesn't take into account an optional index, yet) (and it isn't a real cross-project refactoring tool !).

The function to remove an argument ([here](https://gitlab.com/vindarel/redbaron4emacs/blob/master/red4emacs.el#L253)) shows the list of actual arguments in an ido-completing-read prompt. It's handier than choosing the index. But the backend is also different, not sure this approach would suit emacs-traad.

**Comment by abingham** [comment]
My tendency has been to make the user interface pretty basic to start with. So my approach would be to ask for an index, a name, and a default value. The default value could reasonably default to `None`, though maybe it's better that it defaults to nothing (i.e. it has no default value).

With that said, if you're willing to put in the work to make something nicer, I wouldn't mind. For example, if you could determine how many arguments already exist for the target function and then default the index to the end of the signature, that might be great. (And if so we should consider improving other traad functions, e.g. remove argument).

**Comment by abingham** [comment]
This feature seems to work reasonably well now. I'm going to close it, but if you think it needs further work either reopen this or create a new, more specific issue.
