### ISSUE TITLE
traad-auto-revert appears to do nothing

### ISSUE THREAD

**Issue by talwrii** [abingham/emacs-traad#8]
There is a variable called [traad-auto-revert](https://github.com/abingham/emacs-traad/blob/bfa3d/traad.el#L112). This is unused.

It appears to have got removed while this repository lived inside `traad` itself.

**Comment by abingham** [comment]
Thanks for noticing that. I removed it in 4b84b8b4cf43e1167b3d7fcc51eb7a16b62c26f1. I had plans at some point to allow `emacs-traad` to automatically revert affected buffers, but I obviously never got around to it. I'm not sure we could do any better than emacs' auto-revert any way, so it may not be worth the effort.
